/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./src/components/Hello.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Test2: typeof import('./src/components/test2.vue')['default']
    Vlist: typeof import('./src/components/vlist.vue')['default']
  }
}
